#!/sbin/openrc-run
# Copyright 2019 Sony Interactive Entertainment Inc.
# Distributed under the terms of the GNU General Public License v2

name="netbox-rqworker daemon"
description="nnetbox-rqworker daemon"
command=/opt/netbox/netbox/manage.py
command_args=rqworker
command_user=netbox:netbox
directory=/opt/netbox/netbox
error_log=/var/log/netbox/netbox-rcworker.log
output_log=/var/log/netbox/"${RC_SVCNAME}".log
supervisor=supervise-daemon
