--- live-build/Makefile	2022-06-13 19:21:33.158185611 +0200
+++ live-build/Makefile	2022-06-13 19:23:40.925897928 +0200
@@ -39,27 +39,27 @@
 
 install:
 	# Installing shared data
-	mkdir -p $(DESTDIR)/usr/share/live/build
-	cp -r data functions $(DESTDIR)/usr/share/live/build
-	sed -e 's/.*(\(.*\)).*/\1/; s/^[0-9]://; q' debian/changelog >$(DESTDIR)/usr/share/live/build/VERSION
-	cp -r share/* $(DESTDIR)/usr/share/live/build
+	mkdir -p $(DESTDIR)/$(datadir)/live/build
+	cp -r data functions $(DESTDIR)/$(datadir)/live/build
+	sed -e 's/.*(\(.*\)).*/\1/; s/^[0-9]://; q' debian/changelog >$(DESTDIR)/$(datadir)/live/build/VERSION
+	cp -r share/* $(DESTDIR)/$(datadir)/live/build
 
 	# Installing executables
-	mkdir -p $(DESTDIR)/usr/bin
-	cp -a frontend/* $(DESTDIR)/usr/bin
+	mkdir -p $(DESTDIR)/$(bindir)
+	cp -a frontend/* $(DESTDIR)/$(bindir)
 
-	mkdir -p $(DESTDIR)/usr/lib/live
-	cp -a scripts/* $(DESTDIR)/usr/lib/live
+	mkdir -p $(DESTDIR)/$(libdir)
+	cp -a scripts/* $(DESTDIR)/$(libdir)
 
 	# Installing documentation
-	mkdir -p $(DESTDIR)/usr/share/doc/live-build
-	cp -r COPYING examples $(DESTDIR)/usr/share/doc/live-build
+	mkdir -p $(DESTDIR)/$(docdir)
+	cp -r COPYING examples $(DESTDIR)/$(docdir)
 
 	# Installing manpages
 	for MANPAGE in manpages/en/*; \
 	do \
 		SECTION="$$(basename $${MANPAGE} | awk -F. '{ print $$2 }')"; \
-		install -D -m 0644 $${MANPAGE} $(DESTDIR)/usr/share/man/man$${SECTION}/$$(basename $${MANPAGE}); \
+		install -D -m 0644 $${MANPAGE} $(DESTDIR)/$(mandir)/man$${SECTION}/$$(basename $${MANPAGE}); \
 	done
 
 	for LANGUAGE in $(LANGUAGES); \
@@ -67,26 +67,26 @@
 		for MANPAGE in manpages/$${LANGUAGE}/*; \
 		do \
 			SECTION="$$(basename $${MANPAGE} | awk -F. '{ print $$3 }')"; \
-			install -D -m 0644 $${MANPAGE} $(DESTDIR)/usr/share/man/$${LANGUAGE}/man$${SECTION}/$$(basename $${MANPAGE} .$${LANGUAGE}.$${SECTION}).$${SECTION}; \
+			install -D -m 0644 $${MANPAGE} $(DESTDIR)/$(mandir)/$${LANGUAGE}/man$${SECTION}/$$(basename $${MANPAGE} .$${LANGUAGE}.$${SECTION}).$${SECTION}; \
 		done; \
 	done
 
 uninstall:
 	# Uninstalling shared data
-	rm -rf $(DESTDIR)/usr/share/live/build
-	rmdir --ignore-fail-on-non-empty $(DESTDIR)/usr/share/live > /dev/null 2>&1 || true
+	rm -rf $(DESTDIR)/$(datadir)/live/build
+	rmdir --ignore-fail-on-non-empty $(DESTDIR)/$(datadir)/live > /dev/null 2>&1 || true
 
 	# Uninstalling executables
-	rm -f $(DESTDIR)/usr/bin/lb $(DESTDIR)/usr/bin/live-build
+	rm -f $(DESTDIR)/$(bindir)/lb $(DESTDIR)/$(bindir)/live-build
 
 	# Uninstalling documentation
-	rm -rf $(DESTDIR)/usr/share/doc/live-build
+	rm -rf $(DESTDIR)/$(docdir)
 
 	# Uninstalling manpages
 	for MANPAGE in manpages/en/*; \
 	do \
 		SECTION="$$(basename $${MANPAGE} | awk -F. '{ print $$2 }')"; \
-		rm -f $(DESTDIR)/usr/share/man/man$${SECTION}/$$(basename $${MANPAGE} .en.$${SECTION}).$${SECTION}; \
+		rm -f $(DESTDIR)/$(mandir)/man$${SECTION}/$$(basename $${MANPAGE} .en.$${SECTION}).$${SECTION}; \
 	done
 
 	for LANGUAGE in $(LANGUAGES); \
@@ -94,7 +94,7 @@
 		for MANPAGE in manpages/$${LANGUAGE}/*; \
 		do \
 			SECTION="$$(basename $${MANPAGE} | awk -F. '{ print $$3 }')"; \
-			rm -f $(DESTDIR)/usr/share/man/$${LANGUAGE}/man$${SECTION}/$$(basename $${MANPAGE} .$${LANGUAGE}.$${SECTION}).$${SECTION}; \
+			rm -f $(DESTDIR)/$(mandir)/$${LANGUAGE}/man$${SECTION}/$$(basename $${MANPAGE} .$${LANGUAGE}.$${SECTION}).$${SECTION}; \
 		done; \
 	done
